name: CI

on:
  push:
    branches: [ main ]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: |
            package-lock.json

      - name: Install deps
        run: npm ci

      # These run only if you add the scripts later; harmless otherwise
      - name: Lint (if configured)
        run: npm run lint --if-present

      - name: Test (if configured)
        run: npm test --if-present
